### ISSUE TITLE
Incorrect decimal value: '1999-06-01 00:00:00' for column

### ISSUE THREAD

**Issue by ivanionut** [coldbox-modules/qb#140]
Hi @elpete ,
I found the following error with `qb 8.4.5` and `lucee@5.3.8-SNAPSHOT+117`. The problem does not occur with `lucee@5.3.6+61`

Case:

`qb.from( "orders_products" ).insert( arguments.arrCart );`

`arguments.arrCart` :

![arguments.arrCart](https://hostr.co/file/IqXpJI2JSrTa/arrcart.png)

**ERROR**:

![error](https://hostr.co/file/bhWuwTCFSG0n/errorqb.png)

this is the table `orders_products`:

```sql
CREATE TABLE `orders_products` (
  `order_product_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` int(11) unsigned NOT NULL,
  `product_id` int(11) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `quantity` smallint(5) unsigned NOT NULL,
  `price` decimal(15,2) NOT NULL,
  `total` decimal(15,2) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_product_id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

**Comment by elpete** [comment]
Hey, there!  So, it looks like your total is being passed as a string for some reason instead of a number like your `price` field.  So, qb ignores it when checking if it should be a number.  Then the date checking kicks in.  There is a [strict date detection](https://qb.ortusbooks.com/query-builder/building-queries/parameters-and-bindings#strict-date-detection) you could turn on that would skip the unfortunate date parsing.

In qb, you can always pass the SQL type you would like by passing a query param struct instead of the raw value.
```
qb.from( "orders_products" ).insert( {
    "name": "product title",
    "orderId": 63,
    "price": { "value": 6.99, "cfsqltype": "CF_SQL_DECIMAL" },
    "productId": 10,
    "quantity": 1,
    "total": { "value": 6.99, "cfsqltype": "CF_SQL_DECIMAL" }
} );
```
This might even be more preferable than parsing the total as a number correctly since the default numeric type for qb is `CF_SQL_NUMERIC` (though [this can be changed in `moduleSettings`](https://qb.ortusbooks.com/query-builder/building-queries/parameters-and-bindings#numeric-sql-type)).

So, in review you do any of the following:
1. Make sure your `total` key is being set as a number by Lucee
2. Turn on `strictDateDetection` to avoid any strings from being parsed as numbers
3. Pass an explicit query param struct to set your desired SQL type.
