### ISSUE TITLE
Schema try/catch blocks

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#204]
When dealing with a large number of column modifications, I usually try to use an .each() statement to deal with them.  I normally use .default(0) with numeric fields so when removing columns I have to drop the constraints first.  This becomes problematic when datatypes are mixed, as string fields don't normally have a default.  While I could force a default to null + nullable, I would rather have a way to use a try/catch to allow a dropConstraint() call to fail, but this doesn't work.  It would be nice if I could pass along a 3rd option to dropConstraint() that told it to fail gracefully by reporting an error message but allowing the flow to continue.  See below:

```
schema.alter( "accounts", function( table ) {
  var columns = [ "portfolioTypeID","fundingSourceID","notes", "bDistIncome", "distAmount","accountSize"]
  columns.each((column)=>{
    try {
      table.dropConstraint( table.default( column ), true  );  //fail gracefully
    } catch(e){ }
    table.dropColumn( column );
  })
});
```

**Comment by elpete** [comment]
The reason the `try`/`catch` doesn't work as you expect is because the exception is thrown when either 1) trying to compile the SQL which is done by the `schema.alter` statement or 2) trying to execute the SQL which is also done by the `schema.alter` statement.

You could make separate alter calls to `try`/`catch` in this situation.
