### ISSUE TITLE
Introduce `unicodeString` and `unicodeText` functions

### ISSUE THREAD

**Issue by elpete** [coldbox-modules/qb#53]
Right now the `SchemaBuilder` does not differentiate between unicode and non-unicode varieties for strings.  These two new functions would handle the `NVARCHAR` type variants leaving the original `string` and `text` functions to handle plain `VARCHAR` type variants.

This should be a fairly straightforward pull request opportunity for someone. (I would be happy to coach it along.)

This _will_ be a breaking change since someone relying on a unicode-safe type from the `string` or `text` functions would need to upgrade.

**Comment by wpdebruin** [comment]
I read some documentation on unicode support and the four engines handle this quite different, which makes it tricky to implement a universal unicodeString function and/or unicodeText.
SQL server: you have to specify nchar, nvarchar and ntext if you want to store anything unicode.
MySQL: afaik there is no concept of nvarchar or ntext. You just have to specify a different characterset for the database if you want to enable unicode (default is already utf-8).  So differentiating between unicodeString and string makes no sense, since you can't do that for individual columns, only for the whole db. Maybe I am wrong, because I just did a quick read on this, but correct me if I am wrong.
Oracle is even more complicated: you can specify a charset so you don't have to use unicode columns, at all, but if you don't want your full database unicoded, you ccould still specify the Nvarchar variants. So actually you don't know if it is necessary to specify nvarchar, but you always can if you want
PostgreSQL is more or less the same as MySQL, no concept of unicode data types
Overview can be found here
https://wiki.ispirer.com/sqlways/sql-server/data-types (at the bottom you can switch to other engines)

So why a unicodeString if it only makes sense in MS SQL and (to a lesser extent) Oracle?
On the other hand, we don't want to use raw for every single nvarchar column in MS SQL, because that would be my default in most cases. I would prefer this and use raw for NON unicode varchar.
Or should we be able to specify what string() does in MSSQL? By means of configuring our dialect for unicode support?

Whatever we can invent, it will always be inconvenient for one of the dialects I am afraid

**Comment by wpdebruin** [comment]
This issue is simular to https://ortussolutions.atlassian.net/browse/QB-3
I agree with Samuel Knowlton it should have a switch for unicode, both on  function and module level. A separate unicodString function might make it more messy, because this unicodeString should allways fail or error for MySQL and Postgres, which is not really what you want in a library like qb
If we would implement a switch like this, it should do nothing for mysql and postgres, or should it fail?
I would say it should do nothing,  but this switch should be well documented with some warnings.

**Comment by elpete** [comment]
If a Grammar doesn't have a column support for `unicodeString` then it should return the same as `string`.  This is currently how other columns work.  For instance, `json` returns a `TEXT` column for MSSQL (since they don't have native JSON support across all versions).

As for a "switch", it's likely that the `unicodeString` will just defer to `string` with `arguments.unicode = true`.  That is also a pattern established in qb.  I prefer methods where I don't have to either 1) have random boolean flags (`table.string( "description", true );`) or 2) be required to use named parameters (`table.string( name = "description", unicode = true );`).

**Comment by elpete** [comment]
Moved to https://ortussolutions.atlassian.net/projects/QB/issues/QB-12
